{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2025-3121",
    "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
    "state": "PUBLISHED",
    "assignerShortName": "VulDB",
    "dateReserved": "2025-04-02T13:35:42.010Z",
    "datePublished": "2025-04-02T22:00:12.390Z",
    "dateUpdated": "2025-04-03T19:26:25.202Z"
  },
  "containers": {
    "cna": {
      "providerMetadata": {
        "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "shortName": "VulDB",
        "dateUpdated": "2025-04-02T22:00:12.390Z"
      },
      "title": "PyTorch torch.jit.jit_module_from_flatbuffer memory corruption",
      "problemTypes": [
        {
          "descriptions": [
            {
              "type": "CWE",
              "cweId": "CWE-119",
              "lang": "en",
              "description": "Memory Corruption"
            },
            {
              "type": "CWE",
              "cweId": "CWE-787",
              "lang": "en",
              "description": "Out-of-bounds Write"
            }
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A vulnerability classified as problematic has been found in PyTorch 2.6.0. Affected is the function torch.jit.jit_module_from_flatbuffer. The manipulation leads to memory corruption. Local access is required to approach this attack."
        }
      ]
    }
  }
}